export const GET_MY_TASKS_LOADING = "GET_MY_TASKS_LOADING";
export const GET_MY_TASKS_SUCCESS = "GET_MY_TASKS_SUCCESS";
export const GET_MY_TASKS_FAIL = "GET_MY_TASKS_FAIL";

export const CHECK_IF_USER_CAN_CREATE_TASK_LOADING = "CHECK_IF_USER_CAN_CREATE_TASK_LOADING";
export const CHECK_IF_USER_CAN_CREATE_TASK_SUCCESS = "CHECK_IF_USER_CAN_CREATE_TASK_SUCCESS";
export const CHECK_IF_USER_CAN_CREATE_TASK_FAIL = "CHECK_IF_USER_CAN_CREATE_TASK_FAIL";

export const GET_MY_PROJECTS_SUCCESS = "GET_MY_PROJECTS_SUCCESS";
export const GET_MY_PROJECTS_LOADING = "GET_MY_PROJECTS_LOADING";
export const GET_MY_PROJECTS_FAIL = "GET_MY_PROJECTS_FAIL";

export const CREATE_NEW_PROJECT_LOADING = "CREATE_NEW_PROJECT_LOADING";
export const CREATE_NEW_PROJECT_SUCCESS = "CREATE_NEW_PROJECT_SUCCESS";
export const CREATE_NEW_PROJECT_FAIL = "CREATE_NEW_PROJECT_FAIL";

export const CREATE_NEW_TASK_LOADING = "CREATE_NEW_TASK_LOADING";
export const CREATE_NEW_TASK_SUCCESS = "CREATE_NEW_TASK_SUCCESS";
export const CREATE_NEW_TASK_FAIL = "CREATE_NEW_TASK_FAIL";

export const GET_TASK_DETAILS_LOADING = "GET_TASK_DETAILS_LOADING";
export const GET_TASK_DETAILS_SUCCESS = "GET_TASK_DETAILS_SUCCESS";
export const GET_TASK_DETAILS_FAIL = "GET_TASK_DETAILS_FAIL";

export const UPDATE_TASK_LOADING = "UPDATE_TASK_LOADING";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";

export const GET_PROJECT_DETAILS_LOADING = "GET_PROJECT_DETAILS_LOADING";
export const GET_PROJECT_DETAILS_SUCCESS = "GET_PROJECT_DETAILS_SUCCESS";
export const GET_PROJECT_DETAILS_FAIL = "GET_PROJECT_DETAILS_FAIL";

export const UPDATE_PROJECT_LOADING = "UPDATE_PROJECT_LOADING";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAIL = "UPDATE_PROJECT_FAIL";
