export const GET_MY_TASKS_LOADING = "GET_MY_TASKS_LOADING";
export const GET_MY_TASKS_SUCCESS = "GET_MY_TASKS_SUCCESS";
export const GET_MY_TASKS_FAIL = "GET_MY_TASKS_FAIL";

export const CHECK_IF_USER_CAN_CREATE_TASK_LOADING = "CHECK_IF_USER_CAN_CREATE_TASK_LOADING";
export const CHECK_IF_USER_CAN_CREATE_TASK_SUCCESS = "CHECK_IF_USER_CAN_CREATE_TASK_SUCCESS";
export const CHECK_IF_USER_CAN_CREATE_TASK_FAIL = "CHECK_IF_USER_CAN_CREATE_TASK_FAIL";

export const GET_MY_PROJECTS_SUCCESS = "GET_MY_PROJECTS_SUCCESS";
export const GET_MY_PROJECTS_LOADING = "GET_MY_PROJECTS_LOADING";
export const GET_MY_PROJECTS_FAIL = "GET_MY_PROJECTS_FAIL";
