export const ACTIVATE_USER_FAIL = "ACTIVATE_USER_FAIL";
export const ACTIVATE_USER_LOADING = "ACTIVATE_USER_LOADING";
export const ACTIVATE_USER_SUCCESS = "ACTIVATE_USER_SUCCESS";

export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_LOADING = "USER_REGISTRATION_LOADING";
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";

export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const CHECK_TOKEN_VALID_LOADING = "CHECK_TOKEN_VALID_LOADING";
export const CHECK_TOKEN_VALID_SUCCESS = "CHECK_TOKEN_VALID_SUCCESS";
export const CHECK_TOKEN_VALID_FAIL = "CHECK_TOKEN_VALID_FAIL";
